version: "3.9"

services:
  db:
    image: postgres:16
    container_name: niramoy_postgres
    environment:
      POSTGRES_USER: niramoy
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: niramoy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_niramoy:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U niramoy -d niramoy_db"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata_niramoy:
