"""initial

Revision ID: 08320a78f754
Revises: 
Create Date: 2026-08-10 19:10:02.167667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08320a78f754'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_name'), 'divisions', ['name'], unique=True)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone_emergency', sa.String(length=40), nullable=True),
    sa.Column('phone_general', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_district'), 'hospitals', ['district'], unique=False)
    op.create_index(op.f('ix_hospitals_is_active'), 'hospitals', ['is_active'], unique=False)
    op.create_index(op.f('ix_hospitals_is_verified'), 'hospitals', ['is_verified'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_hospitals_osm_id'), 'hospitals', ['osm_id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_division_id'), 'districts', ['division_id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_table('hospital_facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('facility_type', sa.String(length=16), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'facility_type', name='uq_hospital_facility')
    )
    op.create_index(op.f('ix_hospital_facilities_facility_type'), 'hospital_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_hospital_facilities_hospital_id'), 'hospital_facilities', ['hospital_id'], unique=False)
    op.create_table('hospital_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_ratings_hospital_id'), 'hospital_ratings', ['hospital_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='patient', nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hospital_id'), 'users', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('is_24h', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulances_district_id'), 'ambulances', ['district_id'], unique=False)
    op.create_index(op.f('ix_ambulances_is_active'), 'ambulances', ['is_active'], unique=False)
    op.create_index(op.f('ix_ambulances_name'), 'ambulances', ['name'], unique=False)
    op.create_index(op.f('ix_ambulances_type'), 'ambulances', ['type'], unique=False)
    op.create_table('bed_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('icu_total', sa.Integer(), nullable=False),
    sa.Column('icu_available', sa.Integer(), nullable=False),
    sa.Column('nicu_total', sa.Integer(), nullable=False),
    sa.Column('nicu_available', sa.Integer(), nullable=False),
    sa.Column('ccu_total', sa.Integer(), nullable=False),
    sa.Column('ccu_available', sa.Integer(), nullable=False),
    sa.Column('hdu_total', sa.Integer(), nullable=False),
    sa.Column('hdu_available', sa.Integer(), nullable=False),
    sa.Column('cost_per_day_icu', sa.Float(), nullable=False),
    sa.Column('cost_per_day_nicu', sa.Float(), nullable=False),
    sa.Column('cost_per_day_ccu', sa.Float(), nullable=False),
    sa.Column('cost_per_day_hdu', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_availability_hospital_id'), 'bed_availability', ['hospital_id'], unique=True)
    op.create_index(op.f('ix_bed_availability_last_updated'), 'bed_availability', ['last_updated'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_hospital_id'), 'reviews', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('update_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('update_type', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='Live', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_history_created_at'), 'update_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_update_history_hospital_id'), 'update_history', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_update_history_status'), 'update_history', ['status'], unique=False)
    op.create_index(op.f('ix_update_history_update_type'), 'update_history', ['update_type'], unique=False)
    op.create_index(op.f('ix_update_history_updated_by_user_id'), 'update_history', ['updated_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_history_updated_by_user_id'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_update_type'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_status'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_hospital_id'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_created_at'), table_name='update_history')
    op.drop_table('update_history')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_hospital_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_bed_availability_last_updated'), table_name='bed_availability')
    op.drop_index(op.f('ix_bed_availability_hospital_id'), table_name='bed_availability')
    op.drop_table('bed_availability')
    op.drop_index(op.f('ix_ambulances_type'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_name'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_is_active'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_district_id'), table_name='ambulances')
    op.drop_table('ambulances')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_hospital_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospital_ratings_hospital_id'), table_name='hospital_ratings')
    op.drop_table('hospital_ratings')
    op.drop_index(op.f('ix_hospital_facilities_hospital_id'), table_name='hospital_facilities')
    op.drop_index(op.f('ix_hospital_facilities_facility_type'), table_name='hospital_facilities')
    op.drop_table('hospital_facilities')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_division_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_hospitals_osm_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_is_verified'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_is_active'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_district'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_divisions_name'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
